package com.dailyme.app.theme

import androidx.compose.ui.graphics.Color

/** "Cyanic Studio" palette, as defined in DESIGN.md. */
object CyanicColors {
    val Surface = Color(0xFF0B1326)
    val SurfaceDim = Color(0xFF0B1326)
    val SurfaceBright = Color(0xFF31394D)
    val SurfaceContainerLowest = Color(0xFF060E20)
    val SurfaceContainerLow = Color(0xFF131B2E)
    val SurfaceContainer = Color(0xFF171F33)
    val SurfaceContainerHigh = Color(0xFF222A3D)
    val SurfaceContainerHighest = Color(0xFF2D3449)
    val OnSurface = Color(0xFFDAE2FD)
    val OnSurfaceVariant = Color(0xFFBACAC6)
    val InverseSurface = Color(0xFFDAE2FD)
    val InverseOnSurface = Color(0xFF283044)
    val Outline = Color(0xFF859491)
    val OutlineVariant = Color(0xFF3C4A47)
    val SurfaceTint = Color(0xFF3ADCCC)
    val Primary = Color(0xFF66FDEC)
    val OnPrimary = Color(0xFF003732)
    val PrimaryContainer = Color(0xFF40E0D0)
    val OnPrimaryContainer = Color(0xFF006058)
    val InversePrimary = Color(0xFF006A62)
    val Secondary = Color(0xFF76D6D5)
    val OnSecondary = Color(0xFF003737)
    val SecondaryContainer = Color(0xFF007F7F)
    val OnSecondaryContainer = Color(0xFFDDFFFE)
    val Tertiary = Color(0xFF84F8FF)
    val OnTertiary = Color(0xFF003739)
    val TertiaryContainer = Color(0xFF00E0E9)
    val OnTertiaryContainer = Color(0xFF005F63)
    val Error = Color(0xFFFFB4AB)
    val OnError = Color(0xFF690005)
    val ErrorContainer = Color(0xFF93000A)
    val OnErrorContainer = Color(0xFFFFDAD6)
    val PrimaryFixed = Color(0xFF61F9E9)
    val PrimaryFixedDim = Color(0xFF3ADCCC)
    val OnPrimaryFixed = Color(0xFF00201D)
    val OnPrimaryFixedVariant = Color(0xFF005049)
    val SecondaryFixed = Color(0xFF93F2F2)
    val SecondaryFixedDim = Color(0xFF76D6D5)
    val OnSecondaryFixed = Color(0xFF002020)
    val OnSecondaryFixedVariant = Color(0xFF004F4F)
    val TertiaryFixed = Color(0xFF63F7FF)
    val TertiaryFixedDim = Color(0xFF00DCE5)
    val OnTertiaryFixed = Color(0xFF002021)
    val OnTertiaryFixedVariant = Color(0xFF004F53)
    val Background = Color(0xFF0B1326)
    val OnBackground = Color(0xFFDAE2FD)
    val SurfaceVariant = Color(0xFF2D3449)

    /** Neon Cyan glow used for active toggles, cursor, and interactive "glow" effects. */
    val GlowCyan = Color(0xFF00F5FF)
}

/**
 * Light complement to [CyanicColors]. DESIGN.md only specifies a dark palette, so this
 * derives a light scheme from the same teal/turquoise tonal family (following Material 3's
 * convention that a light theme's primary equals the dark theme's inversePrimary, and vice versa).
 */
object CyanicLightColors {
    val Surface = Color(0xFFF5FAF9)
    val SurfaceDim = Color(0xFFD5DBD9)
    val SurfaceBright = Color(0xFFF5FAF9)
    val SurfaceContainerLowest = Color(0xFFFFFFFF)
    val SurfaceContainerLow = Color(0xFFEFF4F3)
    val SurfaceContainer = Color(0xFFE9EFED)
    val SurfaceContainerHigh = Color(0xFFE3E9E7)
    val SurfaceContainerHighest = Color(0xFFDDE3E1)
    val OnSurface = Color(0xFF171D1C)
    val OnSurfaceVariant = Color(0xFF3F4947)
    val InverseSurface = Color(0xFF2B3230)
    val InverseOnSurface = Color(0xFFECF2EF)
    val Outline = Color(0xFF6F7977)
    val OutlineVariant = Color(0xFFBFC9C6)
    val SurfaceTint = Color(0xFF006A62)
    val Primary = Color(0xFF006A62)
    val OnPrimary = Color(0xFFFFFFFF)
    val PrimaryContainer = Color(0xFFA0F2E4)
    val OnPrimaryContainer = Color(0xFF00201D)
    val InversePrimary = Color(0xFF66FDEC)
    val Secondary = Color(0xFF006A6A)
    val OnSecondary = Color(0xFFFFFFFF)
    val SecondaryContainer = Color(0xFFB3EBEB)
    val OnSecondaryContainer = Color(0xFF002020)
    val Tertiary = Color(0xFF00696D)
    val OnTertiary = Color(0xFFFFFFFF)
    val TertiaryContainer = Color(0xFF9EEFF4)
    val OnTertiaryContainer = Color(0xFF002021)
    val Error = Color(0xFFBA1A1A)
    val OnError = Color(0xFFFFFFFF)
    val ErrorContainer = Color(0xFFFFDAD6)
    val OnErrorContainer = Color(0xFF410002)
    val Background = Color(0xFFF5FAF9)
    val OnBackground = Color(0xFF171D1C)
    val SurfaceVariant = Color(0xFFDAE5E2)
}
